In [1]:
from mistralai.azure.client import MistralAzure
import pandas as pd

df = pd.read_csv("datasets/product_vendor_combinations.csv")
df

                                  product_name                 vendor_name
0                                    freescout         freescout-help-desk
1                                     civetweb                    CivetWeb
2                                      CPython  Python Software Foundation
3                               GoAnywhere MFT                      Fortra
4                                      Firefox                     Mozilla
...                                        ...                         ...
43815                                 haystack                  deepset-ai
43816  Establishment Billing Management System              SourceCodester
43817                    eWeLink Cloud Service                     CoolKIt
43818                               WANotifier                     Unknown
43819                 Dell Inventory Collector                        Dell

[43820 rows x 2 columns]

In [5]:
df = df.iloc[1000:43820]
df

                                  product_name     vendor_name
1000                       Form Maker by 10Web         Unknown
1001                                      EMUI          Huawei
1002                               TOSRFEC.SYS   Dynabook Inc.
1003                                      Cart      VirtueMart
1004                           Net::CIDR::Lite         STIGTSP
...                                        ...             ...
43815                                 haystack      deepset-ai
43816  Establishment Billing Management System  SourceCodester
43817                    eWeLink Cloud Service         CoolKIt
43818                               WANotifier         Unknown
43819                 Dell Inventory Collector            Dell

[42820 rows x 2 columns]

In [ ]:

endpoint = #https here
api_key = #password here

In [40]:
import time
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

client = MistralAzure(server_url=endpoint, api_key=api_key)

OUTPUT_FILE = Path("response ai.txt")
BATCH_SIZE = 10
MAX_RETRIES = 2
RETRY_DELAY = 5   
BATCH_DELAY = 1  


def api_call(prompt_lines):
    resp = client.chat.complete(
        model="Mistral-Large-3",
        messages=[
            {
                "role": "system",
                "content": (
                    "Use the vendor name and product name to identify the 5 most fitting generic product categories, ranked from most to least specific. "
                    "Respond ONLY with a valid JSON array. Each object must have exactly these keys: "
                    "'Original Vendor', 'Original Product', 'Category_1', 'Category_2', 'Category_3', 'Category_4', 'Category_5'. "
                    "Do not include any extra text, markdown, or explanations outside the JSON array."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"The items to categorize are:\n{prompt_lines}"
                ),
            },
        ],
    )
    return resp.choices[0].message.content

def save_response(response_text, batch_index):
    with OUTPUT_FILE.open("a", encoding="utf-8") as f:
        f.write(f"\n--- Batch starting at row {batch_index} ---\n")
        f.write(response_text)
        f.write("\n")


def api_call_with_retry(prompt_lines, batch_index, expected_count):
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = api_call(prompt_lines)
            return response
        except Exception as e:
            logger.warning(f"Batch {batch_index} attempt {attempt}: API error — {e}")

        if attempt < MAX_RETRIES:
            logger.info(f"Retrying in {RETRY_DELAY}s...")
            time.sleep(RETRY_DELAY)

    logger.error(f"Batch {batch_index}: all {MAX_RETRIES} attempts failed. Skipping.")
    return None


total_rows = len(df)
successful_batches = 0
failed_batches = []

logger.info(f"Starting processing of {total_rows} rows in batches of {BATCH_SIZE}.")

for i in range(0, total_rows, BATCH_SIZE):
    batch = df.iloc[i : i + BATCH_SIZE]

    prompt_data = "\n".join(
        f"Vendor: {row['vendor_name']}, Product: {row['product_name']}"
        for _, row in batch.iterrows()
    )

    logger.info(f"Processing rows {i}–{min(i + BATCH_SIZE, total_rows) - 1} / {total_rows - 1}...")

    response = api_call_with_retry(prompt_data, batch_index=i, expected_count=len(batch))

    if response:
        save_response(response, batch_index=i)
        successful_batches += 1
    else:
        failed_batches.append(i)

    time.sleep(BATCH_DELAY)


logger.info(f"Done. {successful_batches} batches saved to '{OUTPUT_FILE}'.")
if failed_batches:
    logger.warning(f"Failed batch start indices (rows): {failed_batches}")

2026-06-16 15:56:44,558 - INFO - Starting processing of 42820 rows in batches of 10.
2026-06-16 15:56:44,560 - INFO - Processing rows 0–9 / 42819...
2026-06-16 15:56:54,984 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 15:56:55,995 - INFO - Processing rows 10–19 / 42819...
2026-06-16 15:57:06,515 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 15:57:07,521 - INFO - Processing rows 20–29 / 42819...
2026-06-16 15:57:21,192 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 15:57:22,198 - INFO - Processing rows 30–39 / 42819...
2026-06-16 15:57:37,226 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 15:57:38,233 - INFO - Processing rows 40–49 / 42819...
2026-06-16 15:57:53,877 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 15:57:54,890 - INFO - Processing rows 50–59 / 42819...
2026-06-16 15:58:08,729 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 15:58:09,735 - INFO - Processing rows 60–69 / 42819...
2026-06-16 15:58:21,994 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 15:58:23,000 - INFO - Processing rows 70–79 / 42819...
2026-06-16 15:58:40,159 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 15:58:41,168 - INFO - Processing rows 80–89 / 42819...
2026-06-16 15:58:53,949 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 15:58:54,958 - INFO - Processing rows 90–99 / 42819...
2026-06-16 15:59:07,772 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 15:59:08,777 - INFO - Processing rows 100–109 / 42819...
2026-06-16 15:59:28,521 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 15:59:29,527 - INFO - Processing rows 110–119 / 42819...
2026-06-16 15:59:44,579 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 15:59:45,590 - INFO - Processing rows 120–129 / 42819...
2026-06-16 16:00:01,005 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:00:02,012 - INFO - Processing rows 130–139 / 42819...
2026-06-16 16:00:16,516 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:00:17,523 - INFO - Processing rows 140–149 / 42819...
2026-06-16 16:00:32,109 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:00:33,116 - INFO - Processing rows 150–159 / 42819...
2026-06-16 16:00:46,196 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:00:47,203 - INFO - Processing rows 160–169 / 42819...
2026-06-16 16:01:00,445 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:01:01,452 - INFO - Processing rows 170–179 / 42819...
2026-06-16 16:01:15,023 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:01:16,035 - INFO - Processing rows 180–189 / 42819...
2026-06-16 16:01:27,082 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:01:28,088 - INFO - Processing rows 190–199 / 42819...
2026-06-16 16:02:00,090 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:02:01,098 - INFO - Processing rows 200–209 / 42819...
2026-06-16 16:02:17,216 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:02:18,223 - INFO - Processing rows 210–219 / 42819...
2026-06-16 16:02:35,326 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:02:36,336 - INFO - Processing rows 220–229 / 42819...
2026-06-16 16:02:52,781 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:02:53,787 - INFO - Processing rows 230–239 / 42819...
2026-06-16 16:03:11,819 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:03:12,825 - INFO - Processing rows 240–249 / 42819...
2026-06-16 16:03:30,183 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:03:31,190 - INFO - Processing rows 250–259 / 42819...
2026-06-16 16:03:50,439 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:03:51,445 - INFO - Processing rows 260–269 / 42819...
2026-06-16 16:04:06,447 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:04:07,457 - INFO - Processing rows 270–279 / 42819...
2026-06-16 16:04:23,362 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:04:24,375 - INFO - Processing rows 280–289 / 42819...
2026-06-16 16:04:44,486 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:04:45,492 - INFO - Processing rows 290–299 / 42819...
2026-06-16 16:05:01,197 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:05:02,204 - INFO - Processing rows 300–309 / 42819...
2026-06-16 16:05:14,944 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:05:15,950 - INFO - Processing rows 310–319 / 42819...
2026-06-16 16:05:28,868 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:05:29,877 - INFO - Processing rows 320–329 / 42819...
2026-06-16 16:05:49,951 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:05:50,957 - INFO - Processing rows 330–339 / 42819...
2026-06-16 16:06:10,707 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:06:11,712 - INFO - Processing rows 340–349 / 42819...
2026-06-16 16:06:25,796 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:06:26,801 - INFO - Processing rows 350–359 / 42819...
2026-06-16 16:06:54,848 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:06:55,856 - INFO - Processing rows 360–369 / 42819...
2026-06-16 16:07:15,741 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:07:16,747 - INFO - Processing rows 370–379 / 42819...
2026-06-16 16:07:32,488 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:07:33,495 - INFO - Processing rows 380–389 / 42819...
2026-06-16 16:07:46,931 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:07:47,940 - INFO - Processing rows 390–399 / 42819...
2026-06-16 16:08:12,706 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:08:13,714 - INFO - Processing rows 400–409 / 42819...
2026-06-16 16:08:31,509 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:08:32,517 - INFO - Processing rows 410–419 / 42819...
2026-06-16 16:08:59,886 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:09:00,892 - INFO - Processing rows 420–429 / 42819...
2026-06-16 16:09:14,204 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:09:15,210 - INFO - Processing rows 430–439 / 42819...
2026-06-16 16:09:31,889 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:09:32,900 - INFO - Processing rows 440–449 / 42819...
2026-06-16 16:09:44,433 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:09:45,439 - INFO - Processing rows 450–459 / 42819...
2026-06-16 16:09:56,405 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:09:57,410 - INFO - Processing rows 460–469 / 42819...
2026-06-16 16:10:08,507 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:10:09,512 - INFO - Processing rows 470–479 / 42819...
2026-06-16 16:10:38,149 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:10:39,157 - INFO - Processing rows 480–489 / 42819...
2026-06-16 16:10:53,913 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:10:54,920 - INFO - Processing rows 490–499 / 42819...
2026-06-16 16:11:09,406 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:11:10,412 - INFO - Processing rows 500–509 / 42819...
2026-06-16 16:11:23,880 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:11:24,887 - INFO - Processing rows 510–519 / 42819...
2026-06-16 16:12:24,896 - WARNING - Batch 510 attempt 1: API error — The read operation timed out
2026-06-16 16:12:24,897 - INFO - Retrying in 5s...
2026-06-16 16:12:45,560 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:12:46,567 - INFO - Processing rows 520–529 / 42819...
2026-06-16 16:13:04,191 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:13:05,197 - INFO - Processing rows 530–539 / 42819...
2026-06-16 16:13:22,403 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:13:23,410 - INFO - Processing rows 540–549 / 42819...
2026-06-16 16:13:47,528 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:13:48,534 - INFO - Processing rows 550–559 / 42819...
2026-06-16 16:14:02,858 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:14:03,866 - INFO - Processing rows 560–569 / 42819...
2026-06-16 16:14:21,392 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:14:22,400 - INFO - Processing rows 570–579 / 42819...
2026-06-16 16:14:41,287 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:14:42,296 - INFO - Processing rows 580–589 / 42819...
2026-06-16 16:14:58,161 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:14:59,170 - INFO - Processing rows 590–599 / 42819...
2026-06-16 16:15:16,288 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:15:17,294 - INFO - Processing rows 600–609 / 42819...
2026-06-16 16:15:33,314 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:15:34,320 - INFO - Processing rows 610–619 / 42819...
2026-06-16 16:15:50,110 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:15:51,118 - INFO - Processing rows 620–629 / 42819...
2026-06-16 16:16:07,661 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:16:08,667 - INFO - Processing rows 630–639 / 42819...
2026-06-16 16:16:28,562 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:16:29,569 - INFO - Processing rows 640–649 / 42819...
2026-06-16 16:16:49,403 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:16:50,408 - INFO - Processing rows 650–659 / 42819...
2026-06-16 16:17:08,697 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:17:09,703 - INFO - Processing rows 660–669 / 42819...
2026-06-16 16:17:24,398 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:17:25,405 - INFO - Processing rows 670–679 / 42819...
2026-06-16 16:17:40,102 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:17:41,108 - INFO - Processing rows 680–689 / 42819...
2026-06-16 16:17:57,231 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:17:58,237 - INFO - Processing rows 690–699 / 42819...
2026-06-16 16:18:10,132 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:18:11,138 - INFO - Processing rows 700–709 / 42819...
2026-06-16 16:18:44,487 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:18:45,496 - INFO - Processing rows 710–719 / 42819...
2026-06-16 16:19:19,697 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:19:20,705 - INFO - Processing rows 720–729 / 42819...
2026-06-16 16:19:39,284 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:19:40,290 - INFO - Processing rows 730–739 / 42819...
2026-06-16 16:20:02,579 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:20:03,585 - INFO - Processing rows 740–749 / 42819...
2026-06-16 16:20:28,841 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:20:29,848 - INFO - Processing rows 750–759 / 42819...
2026-06-16 16:20:52,362 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:20:53,373 - INFO - Processing rows 760–769 / 42819...
2026-06-16 16:21:14,967 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:21:15,973 - INFO - Processing rows 770–779 / 42819...
2026-06-16 16:21:36,888 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:21:37,894 - INFO - Processing rows 780–789 / 42819...
2026-06-16 16:21:52,362 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:21:53,375 - INFO - Processing rows 790–799 / 42819...
2026-06-16 16:22:17,670 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:22:18,677 - INFO - Processing rows 800–809 / 42819...
2026-06-16 16:22:33,643 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:22:34,652 - INFO - Processing rows 810–819 / 42819...
2026-06-16 16:22:50,406 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:22:51,417 - INFO - Processing rows 820–829 / 42819...
2026-06-16 16:23:10,874 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-16 16:23:11,886 - INFO - Processing rows 830–839 / 42819...

In [3]:
df_final = pd.read_csv("datasets/5 categories.csv")

In [24]:
#2nd time
import time
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

client = MistralAzure(server_url=endpoint, api_key=api_key)

OUTPUT_FILE = Path("response ai.txt")
BATCH_SIZE = 20
MAX_RETRIES = 2
RETRY_DELAY = 5   
BATCH_DELAY = 1  
CATEGORIES = [
    "WordPress / WooCommerce Plugins & Themes",
    "Unclassified / Other",
    "General Software Applications",
    "General CMS Platforms (Non-WordPress)",
    "Networking Hardware (Routers, Switches, Access Points)",
    "Enterprise Software (General Business Applications)",
    "Software Development Libraries & SDKs",
    "Hardware & Electronics (General/Unclassified)",
    "ERP Software",
    "System-on-Chip, Processors & Semiconductor Components",
    "Project & Task Management Software",
    "Operating Systems",
    "CI/CD & DevOps Automation Tools",
    "Identity & Access Management / Authentication Software",
    "Security Information & Vulnerability Management Software",
    "Web Server Software",
    "Industrial Control Systems & PLCs",
    "Web Applications (General/Unclassified)",
    "Monitoring, Logging & Observability Software",
    "Endpoint Security & Antivirus Software",
    "SEO & Digital Marketing Tools",
    "Video Conferencing & Collaboration Software",
    "Data Storage & Backup Software",
    "Artificial Intelligence & Machine Learning Software",
    "Learning Management & Educational Software",
    "Statistical & Data Analysis Software",
    "Productivity & Office Software",
    "E-Commerce Platforms (Standalone)",
    "Network Security & Firewall Software",
    "IT Asset & Endpoint Management Software",
    "IoT Devices & Embedded Systems",
    "API & Integration Tools",
    "Container & Virtualization Platforms",
    "Building Management & Automation Systems",
    "CRM Software",
    "IT Infrastructure & Server Management Software",
    "Video Surveillance & Security Camera Systems",
    "ETL, Data Integration & Business Intelligence Software",
    "System Administration & Scripting Tools",
    "Cloud Infrastructure & Orchestration Software",
    "Image, Photo & Video Editing Software",
    "Database Management Software",
    "Document Management Software",
    "Media Players & Streaming Client Software",
    "Wiki & Knowledge Base Software",
    "FTP & Managed File Transfer Software",
    "Application Server / Middleware",
    "Payment Processing & FinTech Software",
    "Point of Sale (POS) & Retail Management Software",
    "Industrial Automation Hardware & Equipment",
    "Booking & Reservation Systems (Non-WordPress)",
    "Mobile Applications (Android/iOS)",
    "Integrated Development Environments (IDEs) & Code Editors",
    "VoIP & Telephony Systems",
    "Customer Support & Help Desk Software",
    "Cryptography, Encryption & PKI Software",
    "Web Development Frameworks & Frontend Build Tools",
    "Web Browsers & Extensions",
    "Manufacturing Execution Systems & Engineering Software",
    "Inventory & Supply Chain Management Software",
    "VPN & Remote Access Software",
    "Wearable & Consumer Electronics",
    "Restaurant, Hospitality & Food Service Software",
    "Accounting & Financial Management Software",
    "Messaging & Chat Applications",
    "Version Control & Source Code Management Tools",
    "Programming Language Runtimes & Interpreters",
    "Power, Energy & Electrical Equipment",
    "Electronic Health Record & Healthcare Management Software",
    "Firmware (General/Unspecified Device)",
    "Human Resources & Payroll Software",
    "PDF & Document Viewer/Editor Software",
    "Email & Messaging Server Software",
    "Printers & Imaging Hardware",
    "Physical Access Control & Security Hardware",
    "Mobile Device Hardware & Firmware",
    "Networking & HTTP Client Libraries",
    "DNS, Proxy & Network Privacy Tools",
    "Reverse Proxy & Load Balancer Software",
    "Medical Devices & Diagnostic Equipment",
    "Telecommunications & Network Management Software",
    "Legal, Compliance & Privacy Management Software",
    "Event Management & Ticketing Software",
    "Web Forums & Discussion Platforms",
    "Website Builders & Templates",
    "Email Security & Anti-Spam Software",
    "Penetration Testing & Security Assessment Tools",
    "Blockchain & Cryptocurrency Software",
    "Package Managers & Dependency Management Tools",
    "Data Serialization, Parsing & Encoding Libraries",
    "Social Media Management & Integration Tools",
    "Real Estate & Property Management Software",
    "Network Attached Storage (NAS) & Storage Appliances",
    "AI Writing, Content & Code Assistant Tools",
    "Gaming Software & Game Engines",
    "Web Scraping & Data Extraction Tools",
    "Automotive & Vehicle Systems",
    "Government, Nonprofit & Public Sector Systems",
    "Geospatial, Mapping & GIS Software",
    "Secure Shell & Remote Administration Tools",
    "Laboratory & Scientific Instrumentation",
]


def api_call(prompt_lines):
    resp = client.chat.complete(
        model="Mistral-Large-3",
        messages=[
            {
                "role": "system",
                "content": (
                    "Use the vendor name, product name and categories, ranked from most to least specific, "
                    "to identify the most fitting generic product category. "
                    "Respond ONLY with a valid JSON array. Each object must have exactly these keys: "
                    "'Original Vendor', 'Original Product', 'Generic Category'. "
                    "The categories to choose from are: " + ", ".join(CATEGORIES) + "."
                )
            },
            {
                "role": "user",
                "content": (
                    f"The items to categorize are:\n{prompt_lines}"
                ),
            },
        ],
    )
    return resp.choices[0].message.content

def save_response(response_text, batch_index):
    with OUTPUT_FILE.open("a", encoding="utf-8") as f:
        f.write(f"\n--- Batch starting at row {batch_index} ---\n")
        f.write(response_text)
        f.write("\n")


def api_call_with_retry(prompt_lines, batch_index, expected_count):
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = api_call(prompt_lines)
            return response
        except Exception as e:
            logger.warning(f"Batch {batch_index} attempt {attempt}: API error — {e}")

        if attempt < MAX_RETRIES:
            logger.info(f"Retrying in {RETRY_DELAY}s...")
            time.sleep(RETRY_DELAY)

    logger.error(f"Batch {batch_index}: all {MAX_RETRIES} attempts failed. Skipping.")
    return None


total_rows = len(df_final)
successful_batches = 0
failed_batches = []

logger.info(f"Starting processing of {total_rows} rows in batches of {BATCH_SIZE}.")

for i in range(0, total_rows, BATCH_SIZE):
    batch = df_final.iloc[i : i + BATCH_SIZE]

    prompt_data = "\n".join(
        f"Vendor: {row['Original Vendor']}, Product: {row['Original Product']}, Category_1: {row['Category_1']}, Category_2: {row['Category_2']}, Category_3: {row['Category_3']}, Category_4: {row['Category_4']}, Category_5: {row['Category_5']}"
        for _, row in batch.iterrows()
    )

    logger.info(f"Processing rows {i}–{min(i + BATCH_SIZE, total_rows) - 1} / {total_rows - 1}...")

    response = api_call_with_retry(prompt_data, batch_index=i, expected_count=len(batch))

    if response:
        save_response(response, batch_index=i)
        successful_batches += 1
    else:
        failed_batches.append(i)

    time.sleep(BATCH_DELAY)


logger.info(f"Done. {successful_batches} batches saved to '{OUTPUT_FILE}'.")
if failed_batches:
    logger.warning(f"Failed batch start indices (rows): {failed_batches}")

2026-06-19 11:20:11,770 - INFO - Starting processing of 42771 rows in batches of 20.
2026-06-19 11:20:11,770 - INFO - Processing rows 0–19 / 42770...
2026-06-19 11:20:30,461 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:20:31,468 - INFO - Processing rows 20–39 / 42770...
2026-06-19 11:20:47,372 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:20:48,378 - INFO - Processing rows 40–59 / 42770...
2026-06-19 11:21:08,805 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:21:09,816 - INFO - Processing rows 60–79 / 42770...
2026-06-19 11:21:33,950 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:21:34,957 - INFO - Processing rows 80–99 / 42770...
2026-06-19 11:21:50,392 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:21:51,397 - INFO - Processing rows 100–119 / 42770...
2026-06-19 11:22:08,916 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:22:09,922 - INFO - Processing rows 120–139 / 42770...
2026-06-19 11:22:25,410 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:22:26,415 - INFO - Processing rows 140–159 / 42770...
2026-06-19 11:22:45,005 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:22:46,010 - INFO - Processing rows 160–179 / 42770...
2026-06-19 11:23:00,019 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:23:01,024 - INFO - Processing rows 180–199 / 42770...
2026-06-19 11:23:15,612 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:23:16,618 - INFO - Processing rows 200–219 / 42770...
2026-06-19 11:23:38,436 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:23:39,448 - INFO - Processing rows 220–239 / 42770...
2026-06-19 11:23:58,171 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:23:59,176 - INFO - Processing rows 240–259 / 42770...
2026-06-19 11:24:18,799 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:24:19,805 - INFO - Processing rows 260–279 / 42770...
2026-06-19 11:24:38,211 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:24:39,215 - INFO - Processing rows 280–299 / 42770...
2026-06-19 11:25:09,196 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:25:10,202 - INFO - Processing rows 300–319 / 42770...
2026-06-19 11:25:30,928 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:25:31,933 - INFO - Processing rows 320–339 / 42770...
2026-06-19 11:25:49,127 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:25:50,133 - INFO - Processing rows 340–359 / 42770...
2026-06-19 11:26:06,672 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:26:07,678 - INFO - Processing rows 360–379 / 42770...
2026-06-19 11:26:32,123 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:26:33,130 - INFO - Processing rows 380–399 / 42770...
2026-06-19 11:27:00,311 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:27:01,315 - INFO - Processing rows 400–419 / 42770...
2026-06-19 11:27:18,718 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:27:19,724 - INFO - Processing rows 420–439 / 42770...
2026-06-19 11:27:30,047 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:27:31,053 - INFO - Processing rows 440–459 / 42770...
2026-06-19 11:27:45,762 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:27:46,768 - INFO - Processing rows 460–479 / 42770...
2026-06-19 11:27:59,850 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:28:00,855 - INFO - Processing rows 480–499 / 42770...
2026-06-19 11:28:11,949 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:28:12,955 - INFO - Processing rows 500–519 / 42770...
2026-06-19 11:28:23,437 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:28:24,449 - INFO - Processing rows 520–539 / 42770...
2026-06-19 11:28:36,963 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:28:37,971 - INFO - Processing rows 540–559 / 42770...
2026-06-19 11:28:50,715 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:28:51,720 - INFO - Processing rows 560–579 / 42770...
2026-06-19 11:29:02,198 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:29:03,211 - INFO - Processing rows 580–599 / 42770...
2026-06-19 11:29:15,809 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:29:16,815 - INFO - Processing rows 600–619 / 42770...
2026-06-19 11:29:28,538 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:29:29,550 - INFO - Processing rows 620–639 / 42770...
2026-06-19 11:29:40,898 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:29:41,911 - INFO - Processing rows 640–659 / 42770...
2026-06-19 11:29:54,198 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:29:55,208 - INFO - Processing rows 660–679 / 42770...
2026-06-19 11:30:21,238 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:30:22,248 - INFO - Processing rows 680–699 / 42770...
2026-06-19 11:30:37,531 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:30:38,536 - INFO - Processing rows 700–719 / 42770...
2026-06-19 11:30:55,714 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:30:56,718 - INFO - Processing rows 720–739 / 42770...
2026-06-19 11:31:14,798 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:31:15,805 - INFO - Processing rows 740–759 / 42770...
2026-06-19 11:31:28,323 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:31:29,331 - INFO - Processing rows 760–779 / 42770...
2026-06-19 11:31:43,578 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:31:44,584 - INFO - Processing rows 780–799 / 42770...
2026-06-19 11:32:09,053 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:32:10,059 - INFO - Processing rows 800–819 / 42770...
2026-06-19 11:32:21,435 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:32:22,442 - INFO - Processing rows 820–839 / 42770...
2026-06-19 11:32:32,751 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:32:33,756 - INFO - Processing rows 840–859 / 42770...
2026-06-19 11:32:45,172 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:32:46,180 - INFO - Processing rows 860–879 / 42770...
2026-06-19 11:33:00,483 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:33:01,490 - INFO - Processing rows 880–899 / 42770...
2026-06-19 11:33:12,193 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:33:13,197 - INFO - Processing rows 900–919 / 42770...
2026-06-19 11:33:27,099 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:33:28,105 - INFO - Processing rows 920–939 / 42770...
2026-06-19 11:33:38,796 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:33:39,801 - INFO - Processing rows 940–959 / 42770...
2026-06-19 11:33:50,138 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:33:51,143 - INFO - Processing rows 960–979 / 42770...
2026-06-19 11:34:12,485 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:34:13,490 - INFO - Processing rows 980–999 / 42770...
2026-06-19 11:34:31,723 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:34:32,729 - INFO - Processing rows 1000–1019 / 42770...
2026-06-19 11:34:43,501 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:34:44,508 - INFO - Processing rows 1020–1039 / 42770...
2026-06-19 11:34:59,075 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:35:00,081 - INFO - Processing rows 1040–1059 / 42770...
2026-06-19 11:35:24,314 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:35:25,319 - INFO - Processing rows 1060–1079 / 42770...
2026-06-19 11:35:38,378 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:35:39,387 - INFO - Processing rows 1080–1099 / 42770...
2026-06-19 11:35:54,906 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:35:55,911 - INFO - Processing rows 1100–1119 / 42770...
2026-06-19 11:36:07,087 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:36:08,093 - INFO - Processing rows 1120–1139 / 42770...
2026-06-19 11:36:18,859 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:36:19,866 - INFO - Processing rows 1140–1159 / 42770...
2026-06-19 11:36:31,117 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:36:32,123 - INFO - Processing rows 1160–1179 / 42770...
2026-06-19 11:36:46,602 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:36:47,608 - INFO - Processing rows 1180–1199 / 42770...
2026-06-19 11:37:03,412 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:37:04,418 - INFO - Processing rows 1200–1219 / 42770...
2026-06-19 11:37:17,513 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:37:18,518 - INFO - Processing rows 1220–1239 / 42770...
2026-06-19 11:37:34,871 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:37:35,876 - INFO - Processing rows 1240–1259 / 42770...
2026-06-19 11:37:52,152 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:37:53,157 - INFO - Processing rows 1260–1279 / 42770...
2026-06-19 11:38:10,035 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:38:11,041 - INFO - Processing rows 1280–1299 / 42770...
2026-06-19 11:38:24,001 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:38:25,006 - INFO - Processing rows 1300–1319 / 42770...
2026-06-19 11:38:37,422 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:38:38,431 - INFO - Processing rows 1320–1339 / 42770...
2026-06-19 11:39:15,595 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:39:16,602 - INFO - Processing rows 1340–1359 / 42770...
2026-06-19 11:39:32,806 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:39:33,814 - INFO - Processing rows 1360–1379 / 42770...
2026-06-19 11:39:51,017 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:39:52,023 - INFO - Processing rows 1380–1399 / 42770...
2026-06-19 11:40:05,442 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:40:06,447 - INFO - Processing rows 1400–1419 / 42770...
2026-06-19 11:40:19,493 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:40:20,498 - INFO - Processing rows 1420–1439 / 42770...
2026-06-19 11:40:37,698 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:40:38,703 - INFO - Processing rows 1440–1459 / 42770...
2026-06-19 11:40:55,557 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:40:56,562 - INFO - Processing rows 1460–1479 / 42770...
2026-06-19 11:41:11,332 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:41:12,338 - INFO - Processing rows 1480–1499 / 42770...
2026-06-19 11:41:27,501 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:41:28,506 - INFO - Processing rows 1500–1519 / 42770...
2026-06-19 11:41:37,385 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:41:38,392 - INFO - Processing rows 1520–1539 / 42770...
2026-06-19 11:41:51,377 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:41:52,388 - INFO - Processing rows 1540–1559 / 42770...
2026-06-19 11:42:07,797 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:42:08,810 - INFO - Processing rows 1560–1579 / 42770...
2026-06-19 11:42:21,758 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:42:22,764 - INFO - Processing rows 1580–1599 / 42770...
2026-06-19 11:42:48,409 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:42:49,417 - INFO - Processing rows 1600–1619 / 42770...
2026-06-19 11:43:03,306 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:43:04,311 - INFO - Processing rows 1620–1639 / 42770...
2026-06-19 11:43:20,048 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:43:21,056 - INFO - Processing rows 1640–1659 / 42770...
2026-06-19 11:43:36,227 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-19 11:43:37,232 - INFO - Processing rows 1660–1679 / 42770...

In [4]:
#3rd time
import time
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

client = MistralAzure(server_url=endpoint, api_key=api_key)

OUTPUT_FILE = Path("datasets/third ai run.txt")
BATCH_SIZE = 20
MAX_RETRIES = 2
RETRY_DELAY = 5   
BATCH_DELAY = 1  
CATEGORIES = [
    "Vehicles",
    "Machinery",
    "Recreational vehicles",
    "Medical equipment",
    "Gas appliances",
    "Toys",
    "Household appliances",
    "Measuring and weighing equipment (MID)",
    "Measuring equipment (non-MID)",
    "Alarm and fire detection systems",
    "Telephones, smartphones, e-readers, wearables",
    "Televisions, monitors, projectors, LED screens and information kiosks",
    "Audio equipment (players, speakers, headphones, microphones)",
    "Computers, laptops, servers",
    "Telecommunications peripheral equipment, switches, routers, wireless access points, media converters, modems, network firewalls and security equipment",
    "Input/output devices (keyboard, mouse, monitors)",
    "Printers, copiers, scanners",
    "Transformers, power supplies, chargers",
    "Batteries",
    "Power electronics",
    "Energy storage systems",
    "Electric motors and generators",
    "Electronic components",
    "Electrical wires and cables",
    "Switches, plugs, sockets, connectors, switchgear",
    "Communication equipment / transmitting-receiving equipment",
    "Smart devices / home automation",
    "Payment and ticketing machines (i.e. self-service terminals – SSTs)",
    "Electrical devices for personal and recreational use",
    "Other category"
]


def api_call(prompt_lines):
    resp = client.chat.complete(
        model="Mistral-Large-3",
        messages=[
            {
                "role": "system",
                "content": (
                    "Use the vendor name, product name and categories, ranked from most to least specific, "
                    "to identify the most fitting generic product category. "
                    "Respond ONLY with a valid JSON array. Each object must have exactly these keys: "
                    "'Original Vendor', 'Original Product', 'Generic Category'. "
                    "If it does not fit any of the categories, choose 'Other category'."
                    "The categories to choose from are: " + ", ".join(CATEGORIES) + "."
                )
            },
            {
                "role": "user",
                "content": (
                    f"The items to categorize are:\n{prompt_lines}"
                ),
            },
        ],
    )
    return resp.choices[0].message.content

def save_response(response_text, batch_index):
    with OUTPUT_FILE.open("a", encoding="utf-8") as f:
        f.write(f"\n--- Batch starting at row {batch_index} ---\n")
        f.write(response_text)
        f.write("\n")


def api_call_with_retry(prompt_lines, batch_index, expected_count):
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = api_call(prompt_lines)
            return response
        except Exception as e:
            logger.warning(f"Batch {batch_index} attempt {attempt}: API error — {e}")

        if attempt < MAX_RETRIES:
            logger.info(f"Retrying in {RETRY_DELAY}s...")
            time.sleep(RETRY_DELAY)

    logger.error(f"Batch {batch_index}: all {MAX_RETRIES} attempts failed. Skipping.")
    return None


total_rows = len(df_final)
successful_batches = 0
failed_batches = []

logger.info(f"Starting processing of {total_rows} rows in batches of {BATCH_SIZE}.")

for i in range(0, total_rows, BATCH_SIZE):
    batch = df_final.iloc[i : i + BATCH_SIZE]

    prompt_data = "\n".join(
        f"Vendor: {row['Original Vendor']}, Product: {row['Original Product']}, Category_1: {row['Category_1']}, Category_2: {row['Category_2']}, Category_3: {row['Category_3']}, Category_4: {row['Category_4']}, Category_5: {row['Category_5']}"
        for _, row in batch.iterrows()
    )

    logger.info(f"Processing rows {i}–{min(i + BATCH_SIZE, total_rows) - 1} / {total_rows - 1}...")

    response = api_call_with_retry(prompt_data, batch_index=i, expected_count=len(batch))

    if response:
        save_response(response, batch_index=i)
        successful_batches += 1
    else:
        failed_batches.append(i)

    time.sleep(BATCH_DELAY)


logger.info(f"Done. {successful_batches} batches saved to '{OUTPUT_FILE}'.")
if failed_batches:
    logger.warning(f"Failed batch start indices (rows): {failed_batches}")

2026-06-23 22:42:04,534 - INFO - Starting processing of 42700 rows in batches of 20.
2026-06-23 22:42:04,534 - INFO - Processing rows 0–19 / 42699...
2026-06-23 22:42:13,082 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:42:14,094 - INFO - Processing rows 20–39 / 42699...
2026-06-23 22:42:21,366 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:42:22,374 - INFO - Processing rows 40–59 / 42699...
2026-06-23 22:42:28,104 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:42:29,111 - INFO - Processing rows 60–79 / 42699...
2026-06-23 22:42:33,541 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:42:34,547 - INFO - Processing rows 80–99 / 42699...
2026-06-23 22:42:41,614 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:42:42,623 - INFO - Processing rows 100–119 / 42699...
2026-06-23 22:42:51,162 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:42:52,172 - INFO - Processing rows 120–139 / 42699...
2026-06-23 22:42:59,121 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:43:00,127 - INFO - Processing rows 140–159 / 42699...
2026-06-23 22:43:07,296 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:43:08,302 - INFO - Processing rows 160–179 / 42699...
2026-06-23 22:43:14,603 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:43:15,616 - INFO - Processing rows 180–199 / 42699...
2026-06-23 22:43:22,304 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:43:23,310 - INFO - Processing rows 200–219 / 42699...
2026-06-23 22:43:28,872 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:43:29,879 - INFO - Processing rows 220–239 / 42699...
2026-06-23 22:43:36,402 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:43:37,408 - INFO - Processing rows 240–259 / 42699...
2026-06-23 22:43:43,832 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:43:44,844 - INFO - Processing rows 260–279 / 42699...
2026-06-23 22:43:50,990 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:43:51,996 - INFO - Processing rows 280–299 / 42699...
2026-06-23 22:43:57,401 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:43:58,407 - INFO - Processing rows 300–319 / 42699...
2026-06-23 22:44:05,095 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:44:06,102 - INFO - Processing rows 320–339 / 42699...
2026-06-23 22:44:10,832 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:44:11,843 - INFO - Processing rows 340–359 / 42699...
2026-06-23 22:44:19,672 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:44:20,684 - INFO - Processing rows 360–379 / 42699...
2026-06-23 22:44:31,857 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:44:32,865 - INFO - Processing rows 380–399 / 42699...
2026-06-23 22:44:41,088 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:44:42,096 - INFO - Processing rows 400–419 / 42699...
2026-06-23 22:44:49,752 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:44:50,760 - INFO - Processing rows 420–439 / 42699...
2026-06-23 22:45:00,311 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:45:01,317 - INFO - Processing rows 440–459 / 42699...
2026-06-23 22:45:09,327 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:45:10,333 - INFO - Processing rows 460–479 / 42699...
2026-06-23 22:45:17,840 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:45:18,847 - INFO - Processing rows 480–499 / 42699...
2026-06-23 22:45:25,931 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:45:26,939 - INFO - Processing rows 500–519 / 42699...
2026-06-23 22:45:35,129 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:45:36,140 - INFO - Processing rows 520–539 / 42699...
2026-06-23 22:45:43,383 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:45:44,390 - INFO - Processing rows 540–559 / 42699...
2026-06-23 22:45:51,670 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:45:52,677 - INFO - Processing rows 560–579 / 42699...
2026-06-23 22:45:58,798 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:45:59,804 - INFO - Processing rows 580–599 / 42699...
2026-06-23 22:46:05,703 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:46:06,709 - INFO - Processing rows 600–619 / 42699...
2026-06-23 22:46:13,988 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:46:14,995 - INFO - Processing rows 620–639 / 42699...
2026-06-23 22:46:23,515 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:46:24,524 - INFO - Processing rows 640–659 / 42699...
2026-06-23 22:46:32,859 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:46:33,867 - INFO - Processing rows 660–679 / 42699...
2026-06-23 22:46:44,557 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:46:45,563 - INFO - Processing rows 680–699 / 42699...
2026-06-23 22:46:52,396 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:46:53,403 - INFO - Processing rows 700–719 / 42699...
2026-06-23 22:47:00,746 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:47:01,754 - INFO - Processing rows 720–739 / 42699...
2026-06-23 22:47:08,865 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:47:09,873 - INFO - Processing rows 740–759 / 42699...
2026-06-23 22:47:20,729 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:47:21,737 - INFO - Processing rows 760–779 / 42699...
2026-06-23 22:47:30,259 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:47:31,268 - INFO - Processing rows 780–799 / 42699...
2026-06-23 22:47:40,311 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:47:41,319 - INFO - Processing rows 800–819 / 42699...
2026-06-23 22:47:49,149 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:47:50,158 - INFO - Processing rows 820–839 / 42699...
2026-06-23 22:48:00,184 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:48:01,196 - INFO - Processing rows 840–859 / 42699...
2026-06-23 22:48:08,601 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:48:09,607 - INFO - Processing rows 860–879 / 42699...
2026-06-23 22:48:16,781 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:48:17,787 - INFO - Processing rows 880–899 / 42699...
2026-06-23 22:48:23,763 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:48:24,772 - INFO - Processing rows 900–919 / 42699...
2026-06-23 22:48:33,011 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:48:34,018 - INFO - Processing rows 920–939 / 42699...
2026-06-23 22:48:40,998 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:48:42,004 - INFO - Processing rows 940–959 / 42699...
2026-06-23 22:48:52,384 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:48:53,393 - INFO - Processing rows 960–979 / 42699...
2026-06-23 22:49:01,122 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:49:02,127 - INFO - Processing rows 980–999 / 42699...
2026-06-23 22:49:13,704 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:49:14,712 - INFO - Processing rows 1000–1019 / 42699...
2026-06-23 22:49:22,601 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:49:23,615 - INFO - Processing rows 1020–1039 / 42699...
2026-06-23 22:49:31,566 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:49:32,574 - INFO - Processing rows 1040–1059 / 42699...
2026-06-23 22:49:40,997 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:49:42,003 - INFO - Processing rows 1060–1079 / 42699...
2026-06-23 22:49:50,702 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:49:51,715 - INFO - Processing rows 1080–1099 / 42699...
2026-06-23 22:50:00,050 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:50:01,058 - INFO - Processing rows 1100–1119 / 42699...
2026-06-23 22:50:09,183 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:50:10,192 - INFO - Processing rows 1120–1139 / 42699...
2026-06-23 22:50:18,678 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:50:19,685 - INFO - Processing rows 1140–1159 / 42699...
2026-06-23 22:50:27,621 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:50:28,628 - INFO - Processing rows 1160–1179 / 42699...
2026-06-23 22:50:35,740 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:50:36,746 - INFO - Processing rows 1180–1199 / 42699...
2026-06-23 22:50:45,043 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:50:46,048 - INFO - Processing rows 1200–1219 / 42699...
2026-06-23 22:50:53,794 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:50:54,801 - INFO - Processing rows 1220–1239 / 42699...
2026-06-23 22:51:02,914 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:51:03,922 - INFO - Processing rows 1240–1259 / 42699...
2026-06-23 22:51:10,952 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:51:11,959 - INFO - Processing rows 1260–1279 / 42699...
2026-06-23 22:51:19,661 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:51:20,668 - INFO - Processing rows 1280–1299 / 42699...
2026-06-23 22:51:36,035 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:51:37,043 - INFO - Processing rows 1300–1319 / 42699...
2026-06-23 22:51:43,127 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:51:44,139 - INFO - Processing rows 1320–1339 / 42699...
2026-06-23 22:51:56,517 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:51:57,528 - INFO - Processing rows 1340–1359 / 42699...
2026-06-23 22:52:07,035 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:52:08,044 - INFO - Processing rows 1360–1379 / 42699...
2026-06-23 22:52:15,832 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:52:16,841 - INFO - Processing rows 1380–1399 / 42699...
2026-06-23 22:52:23,745 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:52:24,752 - INFO - Processing rows 1400–1419 / 42699...
2026-06-23 22:52:45,465 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:52:46,471 - INFO - Processing rows 1420–1439 / 42699...
2026-06-23 22:52:54,978 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:52:55,984 - INFO - Processing rows 1440–1459 / 42699...
2026-06-23 22:53:08,386 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:53:09,397 - INFO - Processing rows 1460–1479 / 42699...
2026-06-23 22:53:17,478 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:53:18,486 - INFO - Processing rows 1480–1499 / 42699...
2026-06-23 22:53:27,002 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:53:28,009 - INFO - Processing rows 1500–1519 / 42699...
2026-06-23 22:53:38,002 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:53:39,009 - INFO - Processing rows 1520–1539 / 42699...
2026-06-23 22:53:47,863 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:53:48,870 - INFO - Processing rows 1540–1559 / 42699...
2026-06-23 22:53:56,932 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:53:57,938 - INFO - Processing rows 1560–1579 / 42699...
2026-06-23 22:54:05,793 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:54:06,800 - INFO - Processing rows 1580–1599 / 42699...
2026-06-23 22:54:13,538 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:54:14,545 - INFO - Processing rows 1600–1619 / 42699...
2026-06-23 22:54:20,601 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:54:21,607 - INFO - Processing rows 1620–1639 / 42699...
2026-06-23 22:54:28,100 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:54:29,106 - INFO - Processing rows 1640–1659 / 42699...
2026-06-23 22:54:33,479 - INFO - HTTP Request: POST https://ace-studentem.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2026-06-23 22:54:34,486 - INFO - Processing rows 1660–1679 / 42699...