In [1]:
import pandas as pd
original_df = pd.read_csv('datasets/cleaned_vulnerabilities.csv')
original_df

C:\Users\kevin\AppData\Local\Temp\ipykernel_3268\2077655704.py:2: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  original_df = pd.read_csv('datasets/cleaned_vulnerabilities.csv')

,id,description,datePublished,dateUpdated,baseScoreVersion,exploitedSince,baseScoreVector,epss,assigner,aliases,enisaIdVendor,references,enisaIdProduct,baseScore,enisaUuid,description_cleaned,product_name,vendor_name
0,EUVD-2026-24141,FreeScout is a free self-hosted help desk and ...,"Apr 21, 2026, 3:52:39 PM","Apr 21, 2026, 3:52:39 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N,0.0,GitHub_M,CVE-2026-40565\n,[{'id': 'df8ea7fe-ea1b-3f31-a494-89b12dbf0c16'...,https://github.com/freescout-help-desk/freesco...,[{'id': '35cc8fe9-cc82-3bc7-9dda-d8dfd8a9d826'...,6.1,b3a6ee31-e20e-3b1c-a684-768095acc098,"['freescout', 'free', 'selfhosted', 'help', 'd...",freescout,freescout-help-desk
1,EUVD-2026-24138,Vulnerability related to an unquoted search pa...,"Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",4.0,NaN,CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:N/VC:H/VI:H/VA...,0.0,INCIBE,GHSA-9vxj-j2f7-9mgg\nCVE-2026-5789\n,[{'id': '5112208e-9449-3f30-b5a0-bdefa26b6740'...,https://www.incibe.es/en/incibe-cert/notices/a...,[{'id': '4dd00402-1cb8-33d1-91f8-5daf0e5fa5c5'...,8.5,7ed70757-c092-3a0b-99e2-96a7f815201b,"['vulnerability', 'related', 'unquoted', 'sear...",civetweb,CivetWeb
2,EUVD-2026-24136,"The method ""sock_recvfrom_into()"" of ""asyncio....","Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",4.0,NaN,CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA...,0.0,PSF,GHSA-3p9c-22jr-wq4x\nCVE-2026-3298\n,[{'id': '455eddad-0274-38e3-876c-1da485aedea5'...,https://github.com/python/cpython/pull/148809\...,[{'id': '79323943-f5b6-3a59-ac3e-e7849e5be63e'...,8.8,e0f49fce-f7e8-3dfc-b70e-dbc0c058a383,"['method', 'sock_recvfrom_into', 'asyncioproac...",CPython,Python Software Foundation
3,EUVD-2026-24130,User‑Controlled HTTP Header in Fortra's GoAnyw...,"Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L,0.0,Fortra,GHSA-6x5f-r479-qh4p\nCVE-2026-1089\n,[{'id': '2ae1e1ad-e03a-3855-b5d6-a2176c0b31dd'...,https://www.fortra.com/security/advisories/pro...,[{'id': '70404ca1-7e53-3be1-87b1-6dc09b1e4ff2'...,6.5,f1bfb170-4572-33bb-a02c-83c7a5e4ce08,"['usercontrolled', 'http', 'header', 'fortras'...",GoAnywhere MFT,Fortra
4,EUVD-2026-24129,The login limit is not enforced on the SFTP se...,"Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L,0.0,Fortra,GHSA-rpc6-m3h5-gmf2\nCVE-2026-0972\n,[{'id': 'cba00c9f-fa23-3062-a6a5-5709e85421d7'...,https://fortra.com/security/advisories/product...,[{'id': 'd104a637-0939-344c-be4c-448beede3920'...,7.3,3965ce35-f611-3fd6-bc4c-580538b77705,"['login', 'limit', 'enforced', 'sftp', 'servic...",GoAnywhere MFT,Fortra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157669,EUVD-2017-5754,In TP-LINK TL-WR741N / TL-WR741ND 150M Wireles...,"May 17, 2022, 12:22:01 AM","May 17, 2022, 12:22:01 AM",3.0,NaN,CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H,0.0,mitre,CVE-2017-14250\nGHSA-92wp-6hhw-34wq\n,[],https://nvd.nist.gov/vuln/detail/CVE-2017-1425...,[],6.5,007fdfcd-d180-3f15-88e4-0f4721132f7e,"['tplink', 'tlwr741n', 'tlwr741nd', '150m', 'w...",NaN,NaN
157670,EUVD-2021-20912,An issue was discovered in baijiacms v4. There...,"Apr 12, 2022, 12:00:36 AM","Apr 16, 2022, 12:01:11 AM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N,0.0,mitre,GHSA-mhv8-2q5p-jrwx\nCVE-2021-34250\n,[],https://nvd.nist.gov/vuln/detail/CVE-2021-3425...,[],6.5,81bf6756-10c5-3e44-bc85-4fb4f37537e2,"['issue', 'wa', 'discovered', 'baijiacms', 'v4...",NaN,NaN
157671,EUVD-2021-25019,Heap Overflow in BaseBmpSupportLib.,"Mar 4, 2022, 12:00:15 AM","Mar 17, 2022, 12:03:40 AM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H,0.0,TianoCore,CVE-2021-38577\nGHSA-6h2r-64q9-4xhr\n,[],https://www.suse.com/security/cve/CVE-2021-385...,[],9.8,13a7fd91-7ee5-3d95-88fb-e30bc76b5fb9,"['heap', 'overflow', 'basebmpsupportlib']",NaN,NaN
157672,EUVD-2020-23701,saitoha libsixel v1.8.6 was discovered to cont...,"Mar 11, 2022, 12:02:34 AM","Mar 17, 2022, 12:02:07 AM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H,0.0,mitre,CVE-2020-36123\nGHSA-p55f-cqj7-9wjw\n,[],https://github.com/saitoha/libsixel/issues/144...,[],8.8,541806e9-5f44-3532-8dcb-5d850deea223,"['saitoha', 'libsixel', 'v186', 'wa', 'discove...",NaN,NaN
157673,EUVD-2022-28883,"In TightVNC 1.3.10, there is an integer signed...","Jan 27, 2022, 12:00:44 AM","Feb 4, 2022, 12:00:45 AM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H,0.0,mitre,GHSA-cm99-ww6p-q22x\nCVE-2022-23967\n,[],https://www.suse.com/security/cve/CVE-2022-239...,[],9.8,caecdb97-985c-326a-93b7-ca5a0c416353,"['tightvnc', '1310', 'integer', 'signedness', ...",NaN,NaN

In [2]:
import json
import pandas as pd

def extract_json_arrays(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        text = f.read()

    arrays = []
    start = None
    depth = 0
    in_string = False
    escaped = False

    for i, char in enumerate(text):

        if char == "\\" and in_string:
            escaped = not escaped
            continue

        if char == '"' and not escaped:
            in_string = not in_string

        escaped = False

        if in_string:
            continue

        if char == "[":
            if depth == 0:
                start = i
            depth += 1

        elif char == "]":
            depth -= 1

            if depth == 0 and start is not None:
                arrays.append((start, text[start:i + 1]))
                start = None

    return arrays


records = []
failed_blocks = []

for position, block in extract_json_arrays("datasets/secondary ai run.txt"):
    try:
        data = json.loads(block)

        if isinstance(data, list):
            records.extend(data)

    except json.JSONDecodeError as e:
        failed_blocks.append({
            "position": position,
            "error": str(e),
            "content": block
        })

df_final = pd.DataFrame(records)

# Save failed blocks for manual review
if failed_blocks:
    with open("datasets/failed_blocks_2.txt", "w", encoding="utf-8") as f:
        for i, failure in enumerate(failed_blocks, 1):
            f.write(f"===== FAILED BLOCK {i} =====\n")
            f.write(f"Position: {failure['position']}\n")
            f.write(f"Error: {failure['error']}\n\n")
            f.write(failure["content"])
            f.write("\n\n\n")
print(f"Loaded {len(df_final)} rows")
print(f"Found {len(failed_blocks)} failed blocks")

Loaded 42756 rows
Found 5 failed blocks

In [3]:
df_final

,Original Vendor,Original Product,Generic Category
0,freescout-help-desk,freescout,Customer Support & Help Desk Software
1,CivetWeb,civetweb,Web Server Software
2,Python Software Foundation,CPython,Programming Language Runtimes & Interpreters
3,Fortra,GoAnywhere MFT,FTP & Managed File Transfer Software
4,Mozilla,Firefox,Web Browsers & Extensions
...,...,...,...
42751,deepset-ai,haystack,Artificial Intelligence & Machine Learning Sof...
42752,SourceCodester,Establishment Billing Management System,Point of Sale (POS) & Retail Management Software
42753,CoolKIt,eWeLink Cloud Service,IoT Devices & Embedded Systems
42754,Unknown,WANotifier,Messaging & Chat Applications
42755,Dell,Dell Inventory Collector,IT Asset & Endpoint Management Software

In [4]:
# Merge original_df with df_final to add product label based on vendor and product match
df = original_df.merge(
    df_final.rename(columns={
        'Original Vendor': 'vendor_match',
        'Original Product': 'product_match',
        'Generic Category': 'product_label'
    }),
    left_on=['vendor_name', 'product_name'],
    right_on=['vendor_match', 'product_match'],
    how='left'
).drop(columns=['vendor_match', 'product_match'])

print(f"Added product_label column. Rows with product_label: {df['product_label'].notna().sum()}")

Added product_label column. Rows with product_label: 130793

In [5]:
df

,id,description,datePublished,dateUpdated,baseScoreVersion,exploitedSince,baseScoreVector,epss,assigner,aliases,enisaIdVendor,references,enisaIdProduct,baseScore,enisaUuid,description_cleaned,product_name,vendor_name,product_label
0,EUVD-2026-24141,FreeScout is a free self-hosted help desk and ...,"Apr 21, 2026, 3:52:39 PM","Apr 21, 2026, 3:52:39 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N,0.0,GitHub_M,CVE-2026-40565\n,[{'id': 'df8ea7fe-ea1b-3f31-a494-89b12dbf0c16'...,https://github.com/freescout-help-desk/freesco...,[{'id': '35cc8fe9-cc82-3bc7-9dda-d8dfd8a9d826'...,6.1,b3a6ee31-e20e-3b1c-a684-768095acc098,"['freescout', 'free', 'selfhosted', 'help', 'd...",freescout,freescout-help-desk,Customer Support & Help Desk Software
1,EUVD-2026-24138,Vulnerability related to an unquoted search pa...,"Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",4.0,NaN,CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:N/VC:H/VI:H/VA...,0.0,INCIBE,GHSA-9vxj-j2f7-9mgg\nCVE-2026-5789\n,[{'id': '5112208e-9449-3f30-b5a0-bdefa26b6740'...,https://www.incibe.es/en/incibe-cert/notices/a...,[{'id': '4dd00402-1cb8-33d1-91f8-5daf0e5fa5c5'...,8.5,7ed70757-c092-3a0b-99e2-96a7f815201b,"['vulnerability', 'related', 'unquoted', 'sear...",civetweb,CivetWeb,Web Server Software
2,EUVD-2026-24136,"The method ""sock_recvfrom_into()"" of ""asyncio....","Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",4.0,NaN,CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA...,0.0,PSF,GHSA-3p9c-22jr-wq4x\nCVE-2026-3298\n,[{'id': '455eddad-0274-38e3-876c-1da485aedea5'...,https://github.com/python/cpython/pull/148809\...,[{'id': '79323943-f5b6-3a59-ac3e-e7849e5be63e'...,8.8,e0f49fce-f7e8-3dfc-b70e-dbc0c058a383,"['method', 'sock_recvfrom_into', 'asyncioproac...",CPython,Python Software Foundation,Programming Language Runtimes & Interpreters
3,EUVD-2026-24130,User‑Controlled HTTP Header in Fortra's GoAnyw...,"Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L,0.0,Fortra,GHSA-6x5f-r479-qh4p\nCVE-2026-1089\n,[{'id': '2ae1e1ad-e03a-3855-b5d6-a2176c0b31dd'...,https://www.fortra.com/security/advisories/pro...,[{'id': '70404ca1-7e53-3be1-87b1-6dc09b1e4ff2'...,6.5,f1bfb170-4572-33bb-a02c-83c7a5e4ce08,"['usercontrolled', 'http', 'header', 'fortras'...",GoAnywhere MFT,Fortra,FTP & Managed File Transfer Software
4,EUVD-2026-24129,The login limit is not enforced on the SFTP se...,"Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L,0.0,Fortra,GHSA-rpc6-m3h5-gmf2\nCVE-2026-0972\n,[{'id': 'cba00c9f-fa23-3062-a6a5-5709e85421d7'...,https://fortra.com/security/advisories/product...,[{'id': 'd104a637-0939-344c-be4c-448beede3920'...,7.3,3965ce35-f611-3fd6-bc4c-580538b77705,"['login', 'limit', 'enforced', 'sftp', 'servic...",GoAnywhere MFT,Fortra,FTP & Managed File Transfer Software
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159974,EUVD-2017-5754,In TP-LINK TL-WR741N / TL-WR741ND 150M Wireles...,"May 17, 2022, 12:22:01 AM","May 17, 2022, 12:22:01 AM",3.0,NaN,CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H,0.0,mitre,CVE-2017-14250\nGHSA-92wp-6hhw-34wq\n,[],https://nvd.nist.gov/vuln/detail/CVE-2017-1425...,[],6.5,007fdfcd-d180-3f15-88e4-0f4721132f7e,"['tplink', 'tlwr741n', 'tlwr741nd', '150m', 'w...",NaN,NaN,NaN
159975,EUVD-2021-20912,An issue was discovered in baijiacms v4. There...,"Apr 12, 2022, 12:00:36 AM","Apr 16, 2022, 12:01:11 AM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N,0.0,mitre,GHSA-mhv8-2q5p-jrwx\nCVE-2021-34250\n,[],https://nvd.nist.gov/vuln/detail/CVE-2021-3425...,[],6.5,81bf6756-10c5-3e44-bc85-4fb4f37537e2,"['issue', 'wa', 'discovered', 'baijiacms', 'v4...",NaN,NaN,NaN
159976,EUVD-2021-25019,Heap Overflow in BaseBmpSupportLib.,"Mar 4, 2022, 12:00:15 AM","Mar 17, 2022, 12:03:40 AM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H,0.0,TianoCore,CVE-2021-38577\nGHSA-6h2r-64q9-4xhr\n,[],https://www.suse.com/security/cve/CVE-2021-385...,[],9.8,13a7fd91-7ee5-3d95-88fb-e30bc76b5fb9,"['heap', 'overflow', 'basebmpsupportlib']",NaN,NaN,NaN
159977,EUVD-2020-23701,saitoha libsixel v1.8.6 was discovered to cont...,"Mar 11, 2022, 12:02:34 AM","Mar 17, 2022, 12:02:07 AM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H,0.0,mitre,CVE-2020-36123\nGHSA-p55f-cqj7-9wjw\n,[],https://github.com/saitoha/libsixel/issues/144...,[],8.8,541806e9-5f44-3532-8dcb-5d850deea223,"['saitoha', 'libsixel', 'v186', 'wa', 'discove...",NaN,NaN,NaN
159978,EUVD-2022-28883,"In TightVNC 1.3.10, there is an integer signed...","Jan 27, 2022, 12:00:44 AM","Feb 4, 2022, 12:00:45 AM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H,0.0,mitre,GHSA-cm99-ww6p-q22x\nCVE-2022-23967\n,[],https://www.suse.com/security/cve/CVE-2022-239...,[],9.8,caecdb97-985c-326a-93b7-ca5a0c416353,"['tightvnc', '1310', 'integer', 'signedness', ...",NaN,NaN,NaN

In [6]:
df.isna().sum()  # Check for missing values in the new product_label column

id                          0
description                 0
datePublished               0
dateUpdated                 0
baseScoreVersion         1923
exploitedSince         158582
baseScoreVector             0
epss                        0
assigner                    0
aliases                     0
enisaIdVendor               0
references                  0
enisaIdProduct              0
baseScore                   0
enisaUuid                   0
description_cleaned         0
product_name            19648
vendor_name             24992
product_label           29186
dtype: int64

In [7]:
# Check in data why so many missing
df_product = df[df["product_name"].isna()]

Original file already has lots of missing product and vendor names: they get dropped

In [8]:
df = df.dropna(subset=["product_label"])
df.isna().sum()

id                          0
description                 0
datePublished               0
dateUpdated                 0
baseScoreVersion         1043
exploitedSince         129848
baseScoreVector             0
epss                        0
assigner                    0
aliases                     0
enisaIdVendor               0
references                  0
enisaIdProduct              0
baseScore                   0
enisaUuid                   0
description_cleaned         0
product_name                0
vendor_name                 0
product_label               0
dtype: int64

In [9]:
df

,id,description,datePublished,dateUpdated,baseScoreVersion,exploitedSince,baseScoreVector,epss,assigner,aliases,enisaIdVendor,references,enisaIdProduct,baseScore,enisaUuid,description_cleaned,product_name,vendor_name,product_label
0,EUVD-2026-24141,FreeScout is a free self-hosted help desk and ...,"Apr 21, 2026, 3:52:39 PM","Apr 21, 2026, 3:52:39 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N,0.00,GitHub_M,CVE-2026-40565\n,[{'id': 'df8ea7fe-ea1b-3f31-a494-89b12dbf0c16'...,https://github.com/freescout-help-desk/freesco...,[{'id': '35cc8fe9-cc82-3bc7-9dda-d8dfd8a9d826'...,6.1,b3a6ee31-e20e-3b1c-a684-768095acc098,"['freescout', 'free', 'selfhosted', 'help', 'd...",freescout,freescout-help-desk,Customer Support & Help Desk Software
1,EUVD-2026-24138,Vulnerability related to an unquoted search pa...,"Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",4.0,NaN,CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:N/VC:H/VI:H/VA...,0.00,INCIBE,GHSA-9vxj-j2f7-9mgg\nCVE-2026-5789\n,[{'id': '5112208e-9449-3f30-b5a0-bdefa26b6740'...,https://www.incibe.es/en/incibe-cert/notices/a...,[{'id': '4dd00402-1cb8-33d1-91f8-5daf0e5fa5c5'...,8.5,7ed70757-c092-3a0b-99e2-96a7f815201b,"['vulnerability', 'related', 'unquoted', 'sear...",civetweb,CivetWeb,Web Server Software
2,EUVD-2026-24136,"The method ""sock_recvfrom_into()"" of ""asyncio....","Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",4.0,NaN,CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA...,0.00,PSF,GHSA-3p9c-22jr-wq4x\nCVE-2026-3298\n,[{'id': '455eddad-0274-38e3-876c-1da485aedea5'...,https://github.com/python/cpython/pull/148809\...,[{'id': '79323943-f5b6-3a59-ac3e-e7849e5be63e'...,8.8,e0f49fce-f7e8-3dfc-b70e-dbc0c058a383,"['method', 'sock_recvfrom_into', 'asyncioproac...",CPython,Python Software Foundation,Programming Language Runtimes & Interpreters
3,EUVD-2026-24130,User‑Controlled HTTP Header in Fortra's GoAnyw...,"Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L,0.00,Fortra,GHSA-6x5f-r479-qh4p\nCVE-2026-1089\n,[{'id': '2ae1e1ad-e03a-3855-b5d6-a2176c0b31dd'...,https://www.fortra.com/security/advisories/pro...,[{'id': '70404ca1-7e53-3be1-87b1-6dc09b1e4ff2'...,6.5,f1bfb170-4572-33bb-a02c-83c7a5e4ce08,"['usercontrolled', 'http', 'header', 'fortras'...",GoAnywhere MFT,Fortra,FTP & Managed File Transfer Software
4,EUVD-2026-24129,The login limit is not enforced on the SFTP se...,"Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L,0.00,Fortra,GHSA-rpc6-m3h5-gmf2\nCVE-2026-0972\n,[{'id': 'cba00c9f-fa23-3062-a6a5-5709e85421d7'...,https://fortra.com/security/advisories/product...,[{'id': 'd104a637-0939-344c-be4c-448beede3920'...,7.3,3965ce35-f611-3fd6-bc4c-580538b77705,"['login', 'limit', 'enforced', 'sftp', 'servic...",GoAnywhere MFT,Fortra,FTP & Managed File Transfer Software
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159914,EUVD-2024-36450,"Dell Peripheral Manager, versions prior to 1.7...","Jul 31, 2024, 8:25:10 AM","Jul 31, 2024, 1:53:39 PM",3.1,NaN,CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H,0.10,dell,CVE-2024-37127\nGHSA-xqvw-7hh9-jm8v\n,[{'id': '30cd5f39-c87b-358f-91f7-468c03678ac8'...,https://www.dell.com/support/kbdoc/en-us/00022...,[{'id': '7c62f44e-50d1-3074-a5dd-373708eade30'...,7.8,f8927bdc-f7c7-3b9a-bc2b-c1dfd1745b43,"['dell', 'peripheral', 'manager', 'version', '...",Dell Peripheral Manager,Dell,IT Asset & Endpoint Management Software
159915,EUVD-2024-47512,The Slider by 10Web WordPress plugin before 1...,"Jul 31, 2024, 6:00:03 AM","Jul 31, 2024, 1:30:13 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N,0.39,WPScan,GHSA-rh6j-hw6c-hv3x\nCVE-2024-6408\n,[{'id': '40176e2c-1188-395c-b64a-949454bdd148'...,https://wpscan.com/vulnerability/31aaeffb-a752...,[{'id': '5bf633bc-747a-3491-9d94-4e46605d9307'...,5.4,dd4b7636-4bc4-3bbf-96ad-0ef437c43e68,"['slider', '10web', 'wordpress', 'plugin', '12...",Slider by 10Web,Unknown,WordPress / WooCommerce Plugins & Themes
159916,EUVD-2024-48252,A vulnerability was found in code-projects Onl...,"Jul 31, 2024, 10:31:04 AM","Jul 31, 2024, 1:29:51 PM",4.0,NaN,CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA...,0.11,VulDB,CVE-2024-7311\nGHSA-qpfv-2pqx-cqjq\n,[{'id': 'd105cdc5-5c97-380f-88c9-160c2abf6996'...,https://vuldb.com/?id.273203\nhttps://vuldb.co...,[{'id': 'c549f477-2c72-31c2-b424-d8f8f60abcdc'...,6.9,3f64fe34-85d0-3e95-89c9-660b978e5604,"['vulnerability', 'wa', 'found', 'codeprojects...",Online Bus Reservation Site,code-projects,Booking & Reservation Systems (Non-WordPress)
159917,EUVD-2024-48251,A vulnerability was found in SourceCodester Re...,"Jul 31, 2024, 10:00:07 AM","Jul 31, 2024, 1:13:05 PM",4.0,NaN,CVSS:4.0/AV:N/AC:L/AT:N/PR:L/UI:N/VC:N/VI:L/VA...,0.13,VulDB,CVE-2024-7310\nGHSA-8235-8498-xmmj\n,[{'id': 'ef82b568-394a-3b11-a35a-0b0cf37659e4'...,https://vuldb.com/?id.273202\nhttps://vuldb.co...,[{'id': '61098927-59a9-3abb-b147-dddb86706f6c'...,5.3,d1e6b715-fd3f-3e88-97ef-66e862d47d64,"['vulnerability', 'wa', 'found', 'sourcecodest...",Record Management System,SourceCodester,Document Management Software
159918,EUVD-2024-48260,A vulnerability classified as critical has bee...,"Jul 31, 2024, 11:00:08 AM","Jul 31, 2024, 1:05:37 PM",4.0,NaN,CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA...,0.25,VulDB,GHSA-w2gr-9pwc-5pm2\nCVE-2024-7320\n,[{'id': '290163b4-67c5-33a8-9f6e-eb813d7f879e'...,https://vuldb.com/?id.273231\nhttps://vuldb.co...,[{'id': '48228bfe-9c8e-313e-8ade-203448cbb398'...,6.9,954603d9-6741-357c-93a6-40c28ff13d29,"['vulnerability', 'classified', 'critical', 'h...",Online Blood Bank Management System,itsourcecode,Electronic Health Record & Healthcare Manageme...

In [10]:
unique_label = df["product_label"].unique()
print(len(unique_label))
unique_label

351

array(['Customer Support & Help Desk Software', 'Web Server Software',
       'Programming Language Runtimes & Interpreters',
       'FTP & Managed File Transfer Software',
       'Web Browsers & Extensions',
       'IT Asset & Endpoint Management Software',
       'Wiki & Knowledge Base Software', 'VoIP & Telephony Systems',
       'Identity & Access Management / Authentication Software',
       'E-Commerce Platforms (Standalone)',
       'Monitoring, Logging & Observability Software',
       'Artificial Intelligence & Machine Learning Software',
       'Point of Sale (POS) & Retail Management Software',
       'IT Infrastructure & Server Management Software',
       'Learning Management & Educational Software',
       'CI/CD & DevOps Automation Tools',
       'System Administration & Scripting Tools',
       'Networking Hardware (Routers, Switches, Access Points)',
       'WordPress / WooCommerce Plugins & Themes',
       'General CMS Platforms (Non-WordPress)',
       'Package Managers & Dependency Management Tools',
       'PDF & Document Viewer/Editor Software',
       'AI Writing, Content & Code Assistant Tools',
       'Wearable & Consumer Electronics',
       'Version Control & Source Code Management Tools',
       'Printers & Imaging Hardware',
       'Networking & HTTP Client Libraries',
       'Productivity & Office Software', 'Gaming Software & Game Engines',
       'Software Development Libraries & SDKs', 'Operating Systems',
       'Email & Messaging Server Software',
       'Firmware (General/Unspecified Device)',
       'Mobile Applications (Android/iOS)',
       'Penetration Testing & Security Assessment Tools',
       'Container & Virtualization Platforms',
       'Statistical & Data Analysis Software',
       'IoT Devices & Embedded Systems',
       'Industrial Automation Hardware & Equipment',
       'Secure Shell & Remote Administration Tools',
       'Data Storage & Backup Software',
       'Reverse Proxy & Load Balancer Software',
       'Low-Code Application Development Platform', 'CRM Software',
       'Database Management Software', 'API & Integration Tools',
       'Endpoint Security & Antivirus Software',
       'Enterprise Software (General Business Applications)',
       'Integrated Development Environments (IDEs) & Code Editors',
       'Security Information & Vulnerability Management Software',
       'Cryptography, Encryption & PKI Software',
       'Booking & Reservation Systems (Non-WordPress)',
       'Web Applications (General/Unclassified)',
       'Automotive & Vehicle Systems', 'Document Management Software',
       'VPN & Remote Access Software',
       'Web Development Frameworks & Frontend Build Tools',
       'Blockchain & Cryptocurrency Software',
       'Project & Task Management Software',
       'Media Players & Streaming Client Software',
       'Image, Photo & Video Editing Software',
       'Data Serialization, Parsing & Encoding Libraries',
       'Web Scraping & Data Extraction Tools',
       'Website Builders & Templates',
       'Telecommunications & Network Management Software',
       'Social Media Management & Integration Tools', 'ERP Software',
       'Network Security & Firewall Software',
       'ETL, Data Integration & Business Intelligence Software',
       'Messaging & Chat Applications',
       'Industrial Control Systems & PLCs',
       'Hardware & Electronics (General/Unclassified)',
       'Network Attached Storage (NAS) & Storage Appliances',
       'Accounting & Financial Management Software',
       'Email Security & Anti-Spam Software', 'Web Browser & Extensions',
       'Electronic Health Record & Healthcare Management Software',
       'System-on-Chip, Processors & Semiconductor Components',
       'Inventory & Supply Chain Management Software',
       'Unclassified / Other',
       'Video Surveillance & Security Camera Systems',
       'Physical Access Control & Security Hardware',
       'Cloud Infrastructure & Orchestration Software',
       'SEO & Digital Marketing Tools', 'Application Server / Middleware',
       'Payment Processing & FinTech Software',
       'Video Conferencing & Collaboration Software',
       'Building Management & Automation Systems',
       'Legal, Compliance & Privacy Management Software',
       'General Software Applications',
       'Geospatial, Mapping & GIS Software',
       'Manufacturing Execution Systems & Engineering Software',
       'Power, Energy & Electrical Equipment',
       'DNS, Proxy & Network Privacy Tools',
       'Human Resources & Payroll Software',
       'Event Management & Ticketing Software',
       'Digital Signage Software', 'Web Forums & Discussion Platforms',
       'Restaurant, Hospitality & Food Service Software',
       'Password Management Software',
       'Real Estate & Property Management Software',
       'Email Marketing Software', 'Reference Management Software',
       'Content Management Systems (CMS)', 'Web Analytics Software',
       'Copyright Management Software', 'Graphic Design Software',
       'Nonprofit & Public Sector Systems',
       'Investment Management Software', 'Marketing Automation Software',
       'Affiliate Marketing Software',
       'Laboratory & Scientific Instrumentation', 'Job Board Software',
       'Digital Asset Management Software',
       'Healthcare Authentication Software', 'Gambling & Betting Tools',
       'Healthcare Management & Electronic Health Record Software',
       'System-on-Chip',
       'Web Application Frameworks & Frontend Build Tools',
       'Media Server Software', 'Filesystem Library',
       'Video Encoding and Processing Software',
       'Government, Nonprofit & Public Sector Systems',
       'Robotic Process Automation (RPA) Software',
       'Download Management Software', 'Password Recovery Tools',
       'Business Management Software',
       'Business Process Management Software',
       'Digital Asset Management (DAM) Software',
       'Workflow Automation Software', 'File Management Software',
       'Download Manager Software', 'Internet Content Filtering Software',
       'Music Production Software', 'Utility Billing Software',
       'Networking & Telecommunications Management Software',
       'Medical Devices & Diagnostic Equipment',
       'Mobile Device Hardware & Firmware',
       'Content Delivery Network (CDN) Tools', 'Accessibility Software',
       'Website Compliance Software', 'Subscription Management Software',
       'Web Compliance Software', 'Digital Publishing Tools',
       'Digital Advertising Software', 'Affiliate Marketing Tools',
       'Financial Trading Tools', 'Chatbot Software',
       'Web Hosting Management Software',
       'Financial Market Analysis Tools',
       'Multimedia Content Applications', 'Health and Fitness Software',
       'Data Integration Tools', 'Content Delivery Network Services',
       'Financial Software', 'Low-Code Development Platforms',
       'Password Recovery Software', 'Web Security Modules',
       'File Sharing Software',
       'Enterprise Content Management (ECM) Software',
       'Applicant Tracking System (ATS)', 'Hotel Management Software',
       'Stream Processing Software', 'Analytics SDK',
       'Job Portal Software', 'Audio Editing Software',
       'Music Production Tools', 'Audio, Photo & Video Editing Software',
       'Multimedia Streaming Software', 'Healthcare Management Systems',
       'Music Software Management Tool', 'Network Operating System',
       'Financial Technology (FinTech)', 'Photo Gallery Software',
       'Data Management Software', 'Contact Management Software',
       'Font Management Software', 'Audio Processing Software',
       'Power Systems Management Software',
       'Networking & Telecommunications Software',
       'Virtualization & Remote Desktop Software',
       'Print Management Software', 'File Archiving Software',
       'Digital Rights Management (DRM) Software',
       'Visitor Management Software',
       'Correctional Facility Management Software',
       'Workflow Automation Tools', 'Streaming Media Server Software',
       'Remote Access Software', 'Media Monitoring Software',
       'Audio Software', 'Content Moderation Tools',
       'Web Security Extensions', 'Robotics Simulation Library',
       'Search Platform Software', 'Web Application Security Software',
       'Enterprise Software', 'Digital Signage Management Software',
       'Digital Signage Media Player', 'Digital Signage Media Players',
       'Digital Signage Management Solutions',
       'Digital Signage Web Platforms',
       'High-Performance Computing Hardware', 'Digital Signage Displays',
       'Digital Signage Systems', 'Blogging Software',
       'Mobile Application Development Software',
       'Low-Code Development Platform', 'Web Security Tools',
       'Low-Code Application Development Platforms',
       'Digital Publishing Platform', 'Programming Language Runtimes',
       'Contractor Management Software', 'Digital Signature Software',
       'Office Automation Software', 'Application Security Tools',
       'Media Library Management Software',
       'Industrial Automation Software',
       'Quality Management Software (QMS)',
       'CDN & Web Performance Software',
       'Virtual Desktop Infrastructure (VDI) Tool',
       'Asset Management Software',
       'Digital Signage Content Management Software',
       'Property Management Systems', 'Data Tape Libraries',
       'Data Integration & Business Intelligence Software',
       'Library Management Software',
       'Library Management & Educational Software',
       'URL Shortener & Link Management Tools', 'Networking Hardware',
       'Product Lifecycle Management Software', 'AV Equipment',
       'Enterprise Resource Planning (ERP) Software',
       'Web Application Firewall',
       'IT Audit & Compliance Management Software', 'Broadcast Equipment',
       'Property Management Software',
       'Recruitment and Staffing Software', 'Localization Software',
       'Facility Management Software', 'Web Application Security Plugin',
       'Healthcare Management Software',
       'Processors & Semiconductor Components', 'Mobile Applications',
       'Enterprise Search Software', 'Business Process Automation Tools',
       'Membership Management Software', 'Gamification Platform',
       'Membership Management Systems', 'Billing and Invoicing Software',
       'Parking Management Software', 'Broadcasting Equipment',
       'Content Management Software', 'Recreational Sports Equipment',
       'Content Management Systems', 'Search Engine Software',
       'Product Lifecycle Management (PLM) Software',
       'Documentation Software', 'Parental Control Software',
       'Pricing Optimization Software', 'Workforce Management Software',
       'Scientific & Data Analysis Software', 'Web Application Builders',
       'Web Performance Optimization Tools',
       'Security Management Systems', 'Search Software',
       'Industrial Plant Management Software',
       'Content Management System', 'User Interface Software',
       'Password Management & Security Tools', 'Remote Access Tools',
       'Energy Management Software', 'Accessibility Tool',
       'Web Application Servers', 'Big Data Processing Tools',
       'Web Application Framework', 'Data Binding Libraries',
       'NoSQL Database', 'IT Service Management (ITSM) Software',
       'Business Process Management (BPM) Software',
       'Low-Code Platform Integration Module', 'GPS Tracking Tools',
       'Email Marketing Tools', 'Time Management Software',
       'CAD Software', 'Emergency Mass Notification System',
       'Financial Services Software', 'Invoicing Software',
       'Live Streaming Software', 'Library Automation Software',
       'Public Access Control Systems', 'Network Monitoring Software',
       'IT Service Management Software',
       'Field Service Management Software', 'Static Site Generator',
       'Business Intelligence Software', 'Web Security Plugin',
       'Quality Management Software',
       'Application Lifecycle Management Software',
       'Governance, Risk, and Compliance (GRC) Software',
       'Video Management Software',
       'Enterprise Asset Management (EAM) Software',
       'Media Management Software', 'Multimedia Software',
       'High-Performance Computing Software', 'Fraud Detection Software',
       'Web Application Security Tools', 'Podcast Analytics Software',
       'Web Development Tools', 'Data Synchronization Software',
       'E-Voting Software', 'Financial Calculation Tools',
       'Issue Tracking Software', 'Affiliate Marketing Plugin',
       'Modeling and Simulation Software', 'Web Accessibility Software',
       'File Management Utilities',
       'Product Information Management Software', 'Web Design Assets',
       'Environmental Management Software', 'Web Security Software',
       'Nutrition Management Tools', 'QR Code Management Software',
       'Peripheral Management Software', 'Recruitment Software',
       'Virtual Reality & Security Camera Systems',
       'Digital Signage Content Management Systems',
       'Financial Trading Software', 'Scientific Measurement Software',
       'Remote Proxy & Load Balancer Software',
       'Content Management System (CMS)', 'System Software',
       'Web Security Tool', 'Workflow Management Software',
       'Community Management Tool', 'Documentation',
       'Mobile Device Management Software',
       'Web Application / Middleware', 'Voice Synthesis Software',
       'Game Modding Tools', 'Job Search Platforms',
       'Music Composition Software', 'Billing & Invoicing Software',
       'Documentation Tools', 'Data Visualization Software',
       'Chatbot Development Frameworks', 'Media Broadcasting Software',
       'Digital Rights Management Software',
       'Professional Audio Equipment',
       'Public Safety & Emergency Management Software',
       'Podcast Management Software'], dtype=object)

This should be not the case, manually look at them

In [11]:
import pandas as pd

# Load the classification mapping
classification = pd.read_csv("datasets/classification.csv")
classification.columns = ["LineNum", "Category", "Status", "MergeTarget"]

# Build a lookup dict: original category -> final category (or None if REMOVE)
def resolve(row):
    if row["Status"] == "MATCH":
        return row["Category"]
    elif row["Status"] == "MERGE":
        return row["MergeTarget"]
    else:  # REMOVE
        return None

classification["FinalCategory"] = classification.apply(resolve, axis=1)
mapping = dict(zip(classification["Category"], classification["FinalCategory"]))

# Apply mapping to your dataframe
df["product_label"] = df["product_label"].map(mapping)

# Drop rows that map to None (i.e. were REMOVE)
df_clean = df.dropna(subset=["product_label"]).copy()

# Optional: rebuild counts/percentages after merging
summary = (
    df_clean["product_label"]
    .value_counts()
    .reset_index()
)
summary.columns = ["Category", "Product Count"]
summary["Percent of Total"] = (
    summary["Product Count"] / summary["Product Count"].sum() * 100
).round(2)

summary.to_csv("datasets/label_distributions.csv", index=False)

C:\Users\kevin\AppData\Local\Temp\ipykernel_3268\1465132816.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["product_label"] = df["product_label"].map(mapping)

In [12]:
unique_label = df["product_label"].unique()
print(len(unique_label))
unique_label

102

array(['Customer Support & Help Desk Software', 'Web Server Software',
       'Programming Language Runtimes & Interpreters',
       'FTP & Managed File Transfer Software',
       'Web Browsers & Extensions',
       'IT Asset & Endpoint Management Software',
       'Wiki & Knowledge Base Software', 'VoIP & Telephony Systems',
       'Identity & Access Management / Authentication Software',
       'E-Commerce Platforms (Standalone)',
       'Monitoring, Logging & Observability Software',
       'Artificial Intelligence & Machine Learning Software',
       'Point of Sale (POS) & Retail Management Software',
       'IT Infrastructure & Server Management Software',
       'Learning Management & Educational Software',
       'CI/CD & DevOps Automation Tools',
       'System Administration & Scripting Tools',
       'Networking Hardware (Routers, Switches, Access Points)',
       'WordPress / WooCommerce Plugins & Themes',
       'General CMS Platforms (Non-WordPress)',
       'Package Managers & Dependency Management Tools',
       'PDF & Document Viewer/Editor Software',
       'AI Writing, Content & Code Assistant Tools',
       'Wearable & Consumer Electronics',
       'Version Control & Source Code Management Tools',
       'Printers & Imaging Hardware',
       'Networking & HTTP Client Libraries',
       'Productivity & Office Software', 'Gaming Software & Game Engines',
       'Software Development Libraries & SDKs', 'Operating Systems',
       'Email & Messaging Server Software',
       'Firmware (General/Unspecified Device)',
       'Mobile Applications (Android/iOS)',
       'Penetration Testing & Security Assessment Tools',
       'Container & Virtualization Platforms',
       'Statistical & Data Analysis Software',
       'IoT Devices & Embedded Systems',
       'Industrial Automation Hardware & Equipment',
       'Secure Shell & Remote Administration Tools',
       'Data Storage & Backup Software',
       'Reverse Proxy & Load Balancer Software', None, 'CRM Software',
       'Database Management Software', 'API & Integration Tools',
       'Endpoint Security & Antivirus Software',
       'Enterprise Software (General Business Applications)',
       'Integrated Development Environments (IDEs) & Code Editors',
       'Security Information & Vulnerability Management Software',
       'Cryptography, Encryption & PKI Software',
       'Booking & Reservation Systems (Non-WordPress)',
       'Web Applications (General/Unclassified)',
       'Automotive & Vehicle Systems', 'Document Management Software',
       'VPN & Remote Access Software',
       'Web Development Frameworks & Frontend Build Tools',
       'Blockchain & Cryptocurrency Software',
       'Project & Task Management Software',
       'Media Players & Streaming Client Software',
       'Image, Photo & Video Editing Software',
       'Data Serialization, Parsing & Encoding Libraries',
       'Web Scraping & Data Extraction Tools',
       'Website Builders & Templates',
       'Telecommunications & Network Management Software',
       'Social Media Management & Integration Tools', 'ERP Software',
       'Network Security & Firewall Software',
       'ETL, Data Integration & Business Intelligence Software',
       'Messaging & Chat Applications',
       'Industrial Control Systems & PLCs',
       'Hardware & Electronics (General/Unclassified)',
       'Network Attached Storage (NAS) & Storage Appliances',
       'Accounting & Financial Management Software',
       'Email Security & Anti-Spam Software',
       'Electronic Health Record & Healthcare Management Software',
       'System-on-Chip, Processors & Semiconductor Components',
       'Inventory & Supply Chain Management Software',
       'Unclassified / Other',
       'Video Surveillance & Security Camera Systems',
       'Physical Access Control & Security Hardware',
       'Cloud Infrastructure & Orchestration Software',
       'SEO & Digital Marketing Tools', 'Application Server / Middleware',
       'Payment Processing & FinTech Software',
       'Video Conferencing & Collaboration Software',
       'Building Management & Automation Systems',
       'Legal, Compliance & Privacy Management Software',
       'General Software Applications',
       'Geospatial, Mapping & GIS Software',
       'Manufacturing Execution Systems & Engineering Software',
       'Power, Energy & Electrical Equipment',
       'DNS, Proxy & Network Privacy Tools',
       'Human Resources & Payroll Software',
       'Event Management & Ticketing Software',
       'Web Forums & Discussion Platforms',
       'Restaurant, Hospitality & Food Service Software',
       'Real Estate & Property Management Software',
       'Government, Nonprofit & Public Sector Systems',
       'Laboratory & Scientific Instrumentation',
       'Medical Devices & Diagnostic Equipment',
       'Mobile Device Hardware & Firmware'], dtype=object)

In [13]:
df.isna().sum()  # Check for missing values in the new product_label column

id                          0
description                 0
datePublished               0
dateUpdated                 0
baseScoreVersion         1043
exploitedSince         129848
baseScoreVector             0
epss                        0
assigner                    0
aliases                     0
enisaIdVendor               0
references                  0
enisaIdProduct              0
baseScore                   0
enisaUuid                   0
description_cleaned         0
product_name                0
vendor_name                 0
product_label             600
dtype: int64

In [14]:
df = df.dropna(subset=["product_label"])
df

,id,description,datePublished,dateUpdated,baseScoreVersion,exploitedSince,baseScoreVector,epss,assigner,aliases,enisaIdVendor,references,enisaIdProduct,baseScore,enisaUuid,description_cleaned,product_name,vendor_name,product_label
0,EUVD-2026-24141,FreeScout is a free self-hosted help desk and ...,"Apr 21, 2026, 3:52:39 PM","Apr 21, 2026, 3:52:39 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N,0.00,GitHub_M,CVE-2026-40565\n,[{'id': 'df8ea7fe-ea1b-3f31-a494-89b12dbf0c16'...,https://github.com/freescout-help-desk/freesco...,[{'id': '35cc8fe9-cc82-3bc7-9dda-d8dfd8a9d826'...,6.1,b3a6ee31-e20e-3b1c-a684-768095acc098,"['freescout', 'free', 'selfhosted', 'help', 'd...",freescout,freescout-help-desk,Customer Support & Help Desk Software
1,EUVD-2026-24138,Vulnerability related to an unquoted search pa...,"Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",4.0,NaN,CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:N/VC:H/VI:H/VA...,0.00,INCIBE,GHSA-9vxj-j2f7-9mgg\nCVE-2026-5789\n,[{'id': '5112208e-9449-3f30-b5a0-bdefa26b6740'...,https://www.incibe.es/en/incibe-cert/notices/a...,[{'id': '4dd00402-1cb8-33d1-91f8-5daf0e5fa5c5'...,8.5,7ed70757-c092-3a0b-99e2-96a7f815201b,"['vulnerability', 'related', 'unquoted', 'sear...",civetweb,CivetWeb,Web Server Software
2,EUVD-2026-24136,"The method ""sock_recvfrom_into()"" of ""asyncio....","Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",4.0,NaN,CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA...,0.00,PSF,GHSA-3p9c-22jr-wq4x\nCVE-2026-3298\n,[{'id': '455eddad-0274-38e3-876c-1da485aedea5'...,https://github.com/python/cpython/pull/148809\...,[{'id': '79323943-f5b6-3a59-ac3e-e7849e5be63e'...,8.8,e0f49fce-f7e8-3dfc-b70e-dbc0c058a383,"['method', 'sock_recvfrom_into', 'asyncioproac...",CPython,Python Software Foundation,Programming Language Runtimes & Interpreters
3,EUVD-2026-24130,User‑Controlled HTTP Header in Fortra's GoAnyw...,"Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L,0.00,Fortra,GHSA-6x5f-r479-qh4p\nCVE-2026-1089\n,[{'id': '2ae1e1ad-e03a-3855-b5d6-a2176c0b31dd'...,https://www.fortra.com/security/advisories/pro...,[{'id': '70404ca1-7e53-3be1-87b1-6dc09b1e4ff2'...,6.5,f1bfb170-4572-33bb-a02c-83c7a5e4ce08,"['usercontrolled', 'http', 'header', 'fortras'...",GoAnywhere MFT,Fortra,FTP & Managed File Transfer Software
4,EUVD-2026-24129,The login limit is not enforced on the SFTP se...,"Apr 21, 2026, 3:32:22 PM","Apr 21, 2026, 3:32:22 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L,0.00,Fortra,GHSA-rpc6-m3h5-gmf2\nCVE-2026-0972\n,[{'id': 'cba00c9f-fa23-3062-a6a5-5709e85421d7'...,https://fortra.com/security/advisories/product...,[{'id': 'd104a637-0939-344c-be4c-448beede3920'...,7.3,3965ce35-f611-3fd6-bc4c-580538b77705,"['login', 'limit', 'enforced', 'sftp', 'servic...",GoAnywhere MFT,Fortra,FTP & Managed File Transfer Software
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159914,EUVD-2024-36450,"Dell Peripheral Manager, versions prior to 1.7...","Jul 31, 2024, 8:25:10 AM","Jul 31, 2024, 1:53:39 PM",3.1,NaN,CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H,0.10,dell,CVE-2024-37127\nGHSA-xqvw-7hh9-jm8v\n,[{'id': '30cd5f39-c87b-358f-91f7-468c03678ac8'...,https://www.dell.com/support/kbdoc/en-us/00022...,[{'id': '7c62f44e-50d1-3074-a5dd-373708eade30'...,7.8,f8927bdc-f7c7-3b9a-bc2b-c1dfd1745b43,"['dell', 'peripheral', 'manager', 'version', '...",Dell Peripheral Manager,Dell,IT Asset & Endpoint Management Software
159915,EUVD-2024-47512,The Slider by 10Web WordPress plugin before 1...,"Jul 31, 2024, 6:00:03 AM","Jul 31, 2024, 1:30:13 PM",3.1,NaN,CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N,0.39,WPScan,GHSA-rh6j-hw6c-hv3x\nCVE-2024-6408\n,[{'id': '40176e2c-1188-395c-b64a-949454bdd148'...,https://wpscan.com/vulnerability/31aaeffb-a752...,[{'id': '5bf633bc-747a-3491-9d94-4e46605d9307'...,5.4,dd4b7636-4bc4-3bbf-96ad-0ef437c43e68,"['slider', '10web', 'wordpress', 'plugin', '12...",Slider by 10Web,Unknown,WordPress / WooCommerce Plugins & Themes
159916,EUVD-2024-48252,A vulnerability was found in code-projects Onl...,"Jul 31, 2024, 10:31:04 AM","Jul 31, 2024, 1:29:51 PM",4.0,NaN,CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA...,0.11,VulDB,CVE-2024-7311\nGHSA-qpfv-2pqx-cqjq\n,[{'id': 'd105cdc5-5c97-380f-88c9-160c2abf6996'...,https://vuldb.com/?id.273203\nhttps://vuldb.co...,[{'id': 'c549f477-2c72-31c2-b424-d8f8f60abcdc'...,6.9,3f64fe34-85d0-3e95-89c9-660b978e5604,"['vulnerability', 'wa', 'found', 'codeprojects...",Online Bus Reservation Site,code-projects,Booking & Reservation Systems (Non-WordPress)
159917,EUVD-2024-48251,A vulnerability was found in SourceCodester Re...,"Jul 31, 2024, 10:00:07 AM","Jul 31, 2024, 1:13:05 PM",4.0,NaN,CVSS:4.0/AV:N/AC:L/AT:N/PR:L/UI:N/VC:N/VI:L/VA...,0.13,VulDB,CVE-2024-7310\nGHSA-8235-8498-xmmj\n,[{'id': 'ef82b568-394a-3b11-a35a-0b0cf37659e4'...,https://vuldb.com/?id.273202\nhttps://vuldb.co...,[{'id': '61098927-59a9-3abb-b147-dddb86706f6c'...,5.3,d1e6b715-fd3f-3e88-97ef-66e862d47d64,"['vulnerability', 'wa', 'found', 'sourcecodest...",Record Management System,SourceCodester,Document Management Software
159918,EUVD-2024-48260,A vulnerability classified as critical has bee...,"Jul 31, 2024, 11:00:08 AM","Jul 31, 2024, 1:05:37 PM",4.0,NaN,CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA...,0.25,VulDB,GHSA-w2gr-9pwc-5pm2\nCVE-2024-7320\n,[{'id': '290163b4-67c5-33a8-9f6e-eb813d7f879e'...,https://vuldb.com/?id.273231\nhttps://vuldb.co...,[{'id': '48228bfe-9c8e-313e-8ade-203448cbb398'...,6.9,954603d9-6741-357c-93a6-40c28ff13d29,"['vulnerability', 'classified', 'critical', 'h...",Online Blood Bank Management System,itsourcecode,Electronic Health Record & Healthcare Manageme...

In [15]:
df['product_label'].value_counts()

product_label
WordPress / WooCommerce Plugins & Themes                  23001
Operating Systems                                         12718
Networking Hardware (Routers, Switches, Access Points)     4820
General CMS Platforms (Non-WordPress)                      3407
Software Development Libraries & SDKs                      3245
                                                          ...
Medical Devices & Diagnostic Equipment                      106
Social Media Management & Integration Tools                  97
Laboratory & Scientific Instrumentation                      77
Mobile Device Hardware & Firmware                            36
General Software Applications                                24
Name: count, Length: 101, dtype: int64

In [14]:
import numpy as np

np.savetxt('datasets/array_vertical.txt', unique_label, fmt='%s')

In [15]:
df.to_csv('datasets/labeled_vulnerabilities.csv', index=False)